Repository GuanceCloud/iacker, pull requests merged in 2023-10, with the labels that each got.

#14 feat: Add template layout for provider initializing
  examples/simple/manifest.cue
  internal/cmd/generate.go
  internal/cue/generator.go
  pkg/rms/v1/rms.cue
  pkg/template/v1/template.cue
  pkg/template/v1/template.pb.go
  pkg/template/v1/template.pb.validate.go
  pkg/template/v1/template.proto
Labels: size/L

#20 chore: Add kubernetes prow integration (owners, labels)
  .github/CODEOWNERS
  OWNERS
  labels.yaml
Labels: size/L

#18 feat: Add Terraform generator
  examples/petstore/manifest.cue
  examples/simple/manifest.cue
  internal/cue/generator.go
  pkg/helpers/naming/naming.cue
  pkg/rms/v1/rms.proto
  templates/terraform/.gitkeep
  templates/terraform/builder/model.cue
  templates/terraform/builder/schema.cue
  templates/terraform/consts.cue
  templates/terraform/datasource/datasource.cue
  templates/terraform/datasource/doc.cue
  templates/terraform/datasource/list.cue
  templates/terraform/datasource/model.cue
  templates/terraform/datasource/operation.cue
  templates/terraform/datasource/schema.cue
  templates/terraform/manifest.cue
  templates/terraform/resource/doc.cue
  templates/terraform/resource/list.cue
  templates/terraform/resource/model.cue
  templates/terraform/resource/operation.cue
  templates/terraform/resource/resource.cue
  templates/terraform/resource/schema.cue
  templates/terraform/tests/manifest.cue
Labels: size/XXL

#22 refactor: Add version for terraform template
  templates/terraform/v1/builder/model.cue
  templates/terraform/v1/builder/schema.cue
  templates/terraform/v1/consts.cue
  templates/terraform/v1/datasource/datasource.cue
  templates/terraform/v1/datasource/doc.cue
  templates/terraform/v1/datasource/list.cue
  templates/terraform/v1/datasource/model.cue
  templates/terraform/v1/datasource/operation.cue
  templates/terraform/v1/datasource/schema.cue
  templates/terraform/v1/manifest.cue
  templates/terraform/v1/resource/doc.cue
  templates/terraform/v1/resource/list.cue
  templates/terraform/v1/resource/model.cue
  templates/terraform/v1/resource/operation.cue
  templates/terraform/v1/resource/resource.cue
  templates/terraform/v1/resource/schema.cue
  templates/terraform/v1/tests/manifest.cue
Labels: approved, size/M

#23 feat: Add proto generator
  templates/proto/v1/godoc.cue
  templates/proto/v1/manifest.cue
  templates/proto/v1/proto.cue
  templates/proto/v1/readme.cue
  templates/proto/v1/tests/manifest.cue
  templates/terraform/v1/builder/model.cue
  templates/terraform/v1/tests/manifest.cue
Labels: size/L, approved

#16 feat: Create necessary documentation menus using nextra
  docs/.gitignore
  docs/LICENSE
  docs/README.md
  docs/components/counters.module.css
  docs/components/counters.tsx
  docs/next-env.d.ts
  docs/next.config.js
  docs/package-lock.json
  docs/package.json
  docs/pages/Explanations/index.mdx
  docs/pages/How-To-Guides/index.mdx
  docs/pages/References/index.mdx
  docs/pages/Tutorials/index.mdx
  docs/pages/_meta.json
  docs/pages/about.mdx
  docs/pages/advanced.mdx
  docs/pages/advanced/satori.mdx
  docs/pages/another.mdx
  docs/pages/index.mdx
  docs/theme.config.tsx
  docs/tsconfig.json
Labels: good first issue, size/XXL, hacktoberfest
